// <auto-generated />
namespace SpellChecker.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class WordsPerTestOnSpellingBeeTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WordsPerTestOnSpellingBeeTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201602111836315_WordsPerTestOnSpellingBeeTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
